SMART_PREEMPTION_CAPABILITIES = {
    "Deterministic Routing": "READY",
    "Cached Dispatch": "READY",
    "Result Cache Reuse": "READY",
    "AI.KB Context Reuse": "READY",
    "Cached Context Reuse": "READY",
    "Reasoning Reuse": "READY",
    "Request Merging": "READY",
    "Duplicate Work Prevention": "READY",
    "Dependency Tracking": "READY",
    "Dependency Waiting": "READY",
    "Parallel Execution": "READY",
    "Agent Coordination": "READY",
    "Task Coordination": "READY",
    "Provider Selection": "READY",
    "Model Selection": "READY",
    "Queue Management": "READY",
    "Runtime State Access": "READY",
    "Performance Tracking": "READY",
    "Failure Recovery": "READY",
    "Dynamic FLASH Updates": "READY",
    "MCP Capability Announcement": "READY",
}


SMART_ACTIVE_POLLING_CAPABILITIES = {
    "Provider Discovery": "READY",
    "Local LLM Service Discovery": "READY",
    "Model Discovery": "READY",
    "Active Model Detection": "READY",
    "Provider Health Monitoring": "READY",
    "Model Availability Tracking": "READY",
    "Runtime State Updates": "READY",
    "Provider Registry Updates": "READY",
    "Model Registry Updates": "READY",
    "Parallel Provider Polling": "READY",
    "Asynchronous Polling": "READY",
    "Off-Hot-Path Polling": "READY",
    "Idle Detection": "READY",
    "Idle Keep-Alive": "READY",
    "Provider Metrics": "READY",
    "Model Metrics": "READY",
    "Dynamic FLASH Updates": "READY",
    "MCP Capability Announcement": "READY",
}