class ReasoningProvider:

    def __init__(self, state):
        self.state = state

    async def connect(self): ...
    async def query_models(self): ...
    async def query_loaded_model(self): ...
    async def refresh_health(self): ...
    async def benchmark(self): ...
    async def keep_alive(self): ...
    async def infer(self, request): ...

    def snapshot(self): ...