SMART_ACTIVE_POLLING_CAPABILITIES = {
    "Local LLM Service Discovery": "READY",
    "Available Model Discovery": "READY",
    "Provider Health Monitoring": "READY",
    "Active Model Detection": "READY",
    "Provider Connection Monitoring": "READY",
    "30-Second Active Polling": "READY",
    "Parallel Provider Polling": "READY",
    "Idle Provider Detection": "READY",
    "Idle Keep-Alive": "READY",
    "Runtime State Updates": "READY",
    "Reasoning Service Registry Updates": "READY",
    "Provider Availability Tracking": "READY",
    "Model Availability Tracking": "READY",
    "Polling Metrics": "READY",
    "Failure Tracking": "READY",
    "Automatic State Refresh": "READY",
    "Boot-Time Discovery": "READY",
    "Boot-Time FLASH Announcement": "READY",
    "Dynamic FLASH Updates": "READY",
    "Cached FLASH Delivery": "READY",
    "MCP Runtime Integration": "READY",
}
